import { app } from 'electron'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import { vaultRoot } from './notes'
import type { McpGenInput } from '../shared/types'

// MCP Builder — Simple Mode. Generates a REAL, runnable stdio MCP server
// scaffold (ping + echo tools) plus docs, into JojoUserData/mcp-servers/<name>.
// Connector-specific tools (Gmail/GitHub/etc.) are left as clearly-marked TODOs
// in the generated code — the scaffold runs; the integration is the user's to
// fill in. Two connectors run with zero scaffolding: files and vault both use
// the official filesystem server via npx.

export interface GenResult {
  folder: string
  files: string[]
  /** ready-to-add MCP server command + args */
  command: string
  args: string[]
  runnableNow: boolean
  note: string
}

const CONNECTOR_NOTES: Record<McpGenInput['connect'], string> = {
  gmail: 'Gmail: requires Google OAuth (client id/secret + refresh token). Never use password login. Start read-only.',
  calendar: 'Google Calendar: OAuth scopes for calendar.readonly first; add write scopes only with confirmation.',
  drive: 'Google Drive: OAuth drive.readonly first. Never sync private files to public repos.',
  github: 'GitHub: use a fine-grained PAT with least privilege. Never commit the token.',
  files: 'Local Files: uses the official @modelcontextprotocol/server-filesystem, scoped to one folder.',
  vault: 'Jojo Vault: exposes your markdown memory folder read/write via the official filesystem server.',
  websearch: 'Web Search: plug in a search API key (Brave, Tavily, etc.) via env var.',
  custom: 'Custom API: wire your own endpoints into the tool handlers below.'
}

function serverTs(input: McpGenInput): string {
  return `// ${input.name} — MCP server (stdio) generated by Jojo OS.
// Permission profile: ${input.permission}. ${CONNECTOR_NOTES[input.connect]}
// Run:  npm i && npx tsx server.ts   (or compile with tsc)
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js'

const server = new Server({ name: '${input.name}', version: '0.1.0' }, { capabilities: { tools: {} } })

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    { name: 'ping', description: 'Health check — returns pong.', inputSchema: { type: 'object', properties: {} } },
    { name: 'echo', description: 'Echo text back (example tool).', inputSchema: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'] } }
    // TODO(${input.connect}): add your real tools here. ${input.permission === 'read' ? 'Keep them read-only.' : 'Guard writes behind confirmation in Jojo.'}
  ]
}))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  try {
    if (req.params.name === 'ping') return { content: [{ type: 'text', text: 'pong' }] }
    if (req.params.name === 'echo') {
      const text = String((req.params.arguments as Record<string, unknown> | undefined)?.text ?? '')
      return { content: [{ type: 'text', text }] }
    }
    throw new Error('Unknown tool: ' + req.params.name)
  } catch (e) {
    return { content: [{ type: 'text', text: 'Error: ' + (e instanceof Error ? e.message : String(e)) }], isError: true }
  }
})

const transport = new StdioServerTransport()
await server.connect(transport)
`
}

function readme(input: McpGenInput): string {
  return `# ${input.name} — MCP server

Generated by Jojo OS (MCP Builder, Simple Mode). Connector: **${input.connect}**. Permission: **${input.permission}**.

${CONNECTOR_NOTES[input.connect]}

## Setup
1. \`npm install\`
2. Fill in \`.env\` from \`.env.example\` (if this connector needs credentials).
3. Implement your real tools in \`server.ts\` (the \`ping\`/\`echo\` tools already work).

## Run
\`\`\`
npx tsx server.ts
\`\`\`

## Add to Jojo
On the **MCP Servers** page: command \`npx\`, args \`-y tsx ${join('<this-folder>', 'server.ts')}\`.
Tools are deny-by-default; enable each one, and every call is confirmed in chat.

## Security notes
- Never commit \`.env\` or any token (see \`.gitignore\`).
- Start read-only; add write tools only with confirmation.
- ${input.permission === 'read' ? 'This profile is read-only.' : 'This profile can write — guard destructive actions.'}
`
}

const pkgJson = (name: string): string =>
  JSON.stringify(
    {
      name: name.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
      version: '0.1.0',
      private: true,
      type: 'module',
      dependencies: { '@modelcontextprotocol/sdk': '^1.29.0' },
      devDependencies: { tsx: '^4.0.0' }
    },
    null,
    2
  )

export function generateMcpServer(input: McpGenInput): GenResult {
  const safe = input.name.replace(/[^a-zA-Z0-9_-]/g, '-') || 'mcp-server'
  const folder = join(app.getPath('userData'), 'JojoUserData', 'mcp-servers', safe)
  if (!existsSync(folder)) mkdirSync(folder, { recursive: true })

  const files: [string, string][] = [
    ['server.ts', serverTs(input)],
    ['README.md', readme(input)],
    ['package.json', pkgJson(input.name)],
    ['.env.example', `# ${input.name} secrets — copy to .env, never commit\n# EXAMPLE_API_KEY=\n`],
    ['.gitignore', 'node_modules/\n.env\n'],
    [
      'PERMISSIONS.md',
      `# Permission profile: ${input.permission}\n\n- read: tools only read data\n- draft: may prepare drafts, never send\n- write-confirm: may write, but Jojo confirms every call\n`
    ]
  ]
  for (const [f, content] of files) writeFileSync(join(folder, f), content)

  // files + vault run today via the official filesystem server (no build).
  if (input.connect === 'files' || input.connect === 'vault') {
    const target = input.connect === 'vault' ? vaultRoot() : folder
    return {
      folder,
      files: files.map((f) => f[0]),
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-filesystem', target],
      runnableNow: true,
      note:
        input.connect === 'vault'
          ? 'Runs now: official filesystem server scoped to your Jojo Vault folder.'
          : 'Runs now: official filesystem server scoped to the generated folder (change the path to any folder).'
    }
  }

  return {
    folder,
    files: files.map((f) => f[0]),
    command: 'npx',
    args: ['-y', 'tsx', join(folder, 'server.ts')],
    runnableNow: false,
    note: 'Scaffold written. Run `npm install` in the folder first, then Start it on the MCP Servers page. The ping/echo tools work; add your connector tools in server.ts.'
  }
}
